name: Workflow of exercise 3
run-name: This is a variable workflow # Optional

# Events triggering the workflow
on: 
  push:
  workflow_dispatch:
# Group of jobs to run as part of the workflow

jobs:
  job_1:
    runs-on: ubuntu-latest
    env:
      JobVariable: "This is a job variable"
    steps:
      - run: echo "${{ env.JobVariable }}"
  job_2:
    runs-on: ubuntu-latest
    env:
      JobVariable: "This is another job variable which is different from the first"
    steps:
      - run: echo "${{ env.JobVariable }}"
  job_3:
    runs-on: ubuntu-latest
    env:
      SECRET_VALUE: ${{ secrets.MY_EDC_SECRET }}
    steps:
      - name: Secret matched
        if: ${{ env.SECRET_VALUE == '2' }}
        run: echo "${{ env.SECRET_VALUE }}"
      - name: Secret did not match
        if: ${{ env.SECRET_VALUE != '2' }}
        run: echo "Did not match 2"