name: Workflow of exercise 6
run-name: 6th workflow # Optional
permissions: {}

on: 
  push:
  workflow_dispatch:

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job`executes in
    container: python:3.14-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pandoc
        run: |
          apt-get update
          apt-get install -y pandoc texlive-latex-base

      - name: Build PDF
        run: pandoc exercises.md -o exercises.pdf

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: exercises-pdf
          path: exercises.pdf
          retention-days: 5
            
     
