name: Workflow of exercise 1
run-name: This is the first workflow # Optional

# Events triggering the workflow
on: [push]
# Group of jobs to run as part of the workflow
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a new message"